config/routes.rb
Rubylearn::Application.routes.draw do

  get "welcome/index"
  root 'welcome#index'

  resources :videos

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	layout "application"

	def index
	end

	def new
	end

	def create
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rubylearn</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/videos/create.html.erb
<h1>New video!</h1>

app/views/videos/index.html.erb
<h1>videos index view</h1>

app/views/videos/new.html.erb
<h1>New video, natch.</h1>
<%= form_for :video, url: videos_path do |v| %>
  <p>
    <%= v.label :title %><br>
    <%= v.text_field :title %>
  </p>
 
  <p>
    <%= v.label :format %><br>
    <%= v.text_field :format %>
  </p>
 
  <p>
    <%= v.submit %>
  </p>
<% end %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<p>This is just me following a simple tutorial, but the fact that my test class was already created for my controller makes me just a little bit giddy.</p>